### ISSUE TITLE
Enhance or Release request.

### ISSUE THREAD

**Issue by Kartikgalhotra** [defparam/smuggler#14]
Hi @defparam,
Recently read about your new finding on zomato. Appreciation
I assume the tool you used "DesyncR" is some other one you created.
Also the payload used were somewhat different.
In near future, would you release a new version including of "Smuggler" including the payloads/ features of "DesyncR" or the DesyncR itself ?

**Comment by defparam** [comment]
"DesyncR" in that report was just a experimental branch of this tool (just different name). There is no difference other than some of the pre-canned payloads. A lot of those payloads I removed or rename because they were considered *niche*. They are the same payloads provided in Burp.
